version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
    ports:
      - 5432:5432
    volumes:
      - "pgdata:/var/lib/postgresql/data"

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - "redis:/data"

  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       - HTTP_PROXY=${http_proxy}
  #       - HTTPS_PROXY=${https_proxy}        
  #   ports:
  #     - "8080:8080"
  #     - "9090:9090"
  #   environment:
  #     - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
  #   depends_on:
  #     - postgres
  #   entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
  #   command: go run main.go

volumes:
  pgdata:
  redis:
